# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd844441a7f068b3dcfd5d63b9312af27bd7fade3545faa32ef2893e048ebb5a6bbf6c8f0affed4eb11c1a2657558cf337708b0517225069eca43a0048f9200

test:
  secret_key_base: 1cac8ce7cab883417e3b375b22796eb251de5c1095c77960511d2e5eae7d68f461ac65cbe40c95818d50590d77290dce7dfd895e8bb53df76415774d78779061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
